name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_APP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Run chatbot
        run: python3 hpvsa.py
      - uses: actions/checkout@v4
      - name: Run chatbot
        run: python3 ohisa.py
      - uses: actions/checkout@v4
      - name: Run chatbot
        run: python3 config_loader.py
      - uses: actions/checkout@v4
      - name: Run chatbot
        run: python3 secret_code_portal.py
        
