name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_APP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug SMTP environment variables
        run: |
          echo "SMTP_USERNAME=$SMTP_USERNAME"
          echo "SMTP_APP_PASSWORD=${SMTP_APP_PASSWORD:+SET}"
          if [ -z "$SMTP_USERNAME" ]; then echo "ERROR: SMTP_USERNAME is not set!"; exit 1; fi
          if [ -z "$SMTP_APP_PASSWORD" ]; then echo "ERROR: SMTP_APP_PASSWORD is not set!"; exit 1; fi
      - name: Run chatbot
        run: python3 config_loader.py
      - name: Run chatbot
        run: python3 secret_code_portal.py
      - name: Run chatbot
        run: python3 HPVSA.py
      - name: Run chatbot
        run: python3 OHISA.py
    
